modLoader="javafml"
loaderVersion="[30,)"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="wtbw_decoration"
version="${file.jarVersion}"
displayName="WTBW Decoration"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="tools.png"
#credits="Thanks for this wtbw mod goes to Java" #optional
authors="Naxanria, Sunekaer"
description='''
Adds new decorative blocks
'''
[[dependencies.wtbw_decoration]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_decoration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_decoration]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"